-- ============================================================
--  TODO: Uber sloppy file which i have yet to sanitize so it doesn't suck
--  This file is the base class from which the rest of the engines will
--  inherit from. It is required by other modules which will 
--  eventually be created. All downstream modules read from a data bus
--  without knowing which layout produced it.
--
--  ── Class hierarchy ───────────────────────────────────────────
--
--     BlockType           (abstract base — defines interface contract)
--     ├── PistonBlock     (all reciprocating engines, shared physics)
--     │    ├── InlineEngine        layout="inline"
--     │    ├── BoxerEngine         layout="boxer"
--     │    ├── V-TypeEngine        layout="v"         BankAngle required
--     │    ├── WR-TypeEngine       layout="wr"        BankAngle + BankCount
--     │    ├── RotaryEngine        layout="wankel"    Rotary geometry
--     |    ├── RadialEngine        layout="radial"    Radial engines
--     |    ├── SingleMonoEngine    layout="single"    Requires Balance shafts
--     |    └── ParallelTwinEngine  layout="twin"      Requires Balance shafts 
--     ├── TurbineBlock    (layout="turbine")    non-piston superclass
--     └── ElectricBlock   (layout="electric")   non-piston superclass
--
--  ── Virtual method: GetLayoutFactors(params) ─────────────────
--
--  Each layout overrides this to return a flat table of multipliers
--  applied on top of the shared piston geometry math:
--
--    InertiaFactor     – multiplier on flywheel inertia
--    BalanceFactor     – crankshaft balance quality [0-1]; lower means
--                        minimum stable idle RPM is higher
--    TorqueSmoothness  – torque delivery evenness [0-1]; affects misfire
--                        sensitivity and idle roughness
--    BSFCMult          – correction on top of Otto-cycle BSFC
--    IdleRPMMult       – scales the bore/stroke-derived idle RPM
--    VEBonus           – volumetric efficiency offset [-0.1 .. +0.1]
--    FiringIrregularity– fractional deviation from even firing [0-1]
--
--  ── Entity parameters (set in shared.lua / spawner) ──────────
--
--  Piston engines:
--    Layout      string  "inline"|"boxer"|"v"|"wr"|"wankel"|...etc
--    Bore        number  cylinder bore radius (cm)
--    Stroke      number  piston stroke (cm)
--    Clearance   number  TDC dead space (cm)
--    Pistons     number  cylinder count (rotors for Wankel)
--    BankAngle   number  degrees between banks (V, WR)
--    BankCount   number  number of banks (WR only; V is always 2)
--
--  Non-piston engines:
--    Layout      string  "turbine"|"electric"
--    (No Bore/Stroke/Clearance — TypeDef provides all performance data)
--
--  ── Geo table shape (identical for all types) ─────────────────
--
--  All Compute() methods return a geo table with these keys so that
--  Combustion.lua and all downstream modules are layout-agnostic:
--
--    -- Geometry identity
--    Layout, BankAngle, BankCount, IsPiston, IsWankel, IsTurbine, IsElectric
--    -- Input parameters (stored for HUD / GetStatus)
--    BoreCm, StrokeCm, ClearanceCm, Pistons
--    -- Derived geometry (piston only; nil for non-piston)
--    CompressionRatio, SweptVolPerCyl, Displacement
--    -- Performance (all types)
--    PeakTorque, RedlineRPM, IdleRPM
--    BSFC, HeatCoeff, FlywheelInertia
--    TorqueSmoothness, BalanceFactor, FiringIrregularity
--    -- Torque curve (all types)
--    maxTorque, maxRPM, steps, curve
--    -- Sample method (closure over curve)
--    Sample(rpm) → Nm
-- ============================================================

ACF.Classes.DefineClass("ACF.Engines.BlockType", function()
    CLASS.Name          = "Block Type Class"
    CLASS.Description   = "The base class for any and all types of engine blocks."
end)